### ISSUE TITLE
Previous and Next links are not working with r/geochallenges

### ISSUE THREAD

**Issue by eppfel** [LiquidFun/GeoStackr#5]
With moving series to r/geochallengs  the previous and next links are broken, because the links are hardcoded to r/geoguessr. To not break old stacks, a configuration option would help.

https://github.com/LiquidFun/GeoStackr/blob/db41439b760c223061b140d28f3ee2aa3b0b205a/geostackr.py#L239

**Comment by LiquidFun** [comment]
Ah, yes, I forgot to change it. There is already a parameter for the subreddit, I'll fix it soon. Thanks for letting me know!
